- project:
    templates:
      - openstack-python-jobs
      - check-requirements
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-pylint:
            voting: false
        - openstack-tox-py35:
            voting: false
    gate:
      queue: blazar
      jobs:
        - openstack-tox-py35:
            voting: false